name: Build and Run Docker Compose

on:
  push:
    branches: [ az/memray ]
  pull_request:
    branches: [ az/memray ]
  workflow_dispatch:

runs-on: self-hosted


jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: |
          docker build -t cvat-server:latest -f Dockerfile .

      - name: Build UI image
        run: |
          docker build -t cvat-ui:latest -f Dockerfile.ui .

      - name: Show built images
        run: docker images

      - name: Run docker compose
        run: |
          docker compose -f docker-compose-self-build.yml up -d

      - name: Show running containers
        run: docker ps -a
